### ISSUE TITLE
Validations needed

### ISSUE THREAD

**Issue by maurusrv** [saanyan/saanmaycommunitypantry#1]
Hi, I've tried putting a pin in Vietnam and my colleague in Palau, and complete the process of inputting test value on the form. 

The data persisted which is why i'm posting this issue. 

We might need to have some validation flow / feature to make this project a vital source of information. 

Anyway, just saying hi first, and expressing my enthusiasm to develop this further in this pandemic times. Your work is inspiring. :muscle:

**Comment by saanyan** [comment]
Hi, Maurus!
  

  
The pins were deleted earlier around 11PM.
  

  
Thank you so much for your input! We would appreciate your help in improving this!
  

  
Thank you and keep safe!
  
  
  
  
  
  
    
  
Best regards,
  
Andi
  
  
>

**Comment by maurusrv** [comment]
I'll definitely look into it and will try to make a prototype that the community can use. Will update some time somehow. 

Any guidelines just to get some things started? Like tech and feature considerations? 

I'm considering features like: 
1. User would be able to "submit" a community pantry details on the app, and with proper validation, im not sure who can be an admin or some sort of validation team.

2. A feature that revolves in establishing supply sources, as I can see posts in the fb group about it.

3. Maybe a navigation feature / find nearest pantry to be able for individuals to restock and give aid too. 

4. Maybe news or social media aggregation. 

Anyway, i actually got ahead and am able to render the data on a map in a private repo first, by borrowing your cartodb credentials and using the tech stack im comfortable with. 

I guess that's it. Thanks again! #opensource
